### ISSUE TITLE
MainTemplate breaking Podcasts

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#13]
Subdomains of
```
podigee.com
podigee.net
podigee.io
````
are usually podcasts the user is interested in.
Sure there is a bit of analytics and advertising involved but the domains mostly serve valid content , the ads are inside the podcast audio files and the tracking analytics be done via server logs like any other website.

**Comment by KodoPengin** [comment]
Any example where these addresses are actively used?

Would like to check them again.

**Comment by yoshimo** [comment]
```siblersdenkraeume.podigee.io``` is a CNAME for ```io.podigee.net``` which is on the list

**Comment by KodoPengin** [comment]
player.podigee-cdn.net # (untouched - Playertheme, JS, CSS, Fonts)
www.podigee.com # (untouched - Assets)
main.podigee-cdn.net # (untouched - Mediafiles/Stream)
images.podigee-cdn.net # (Teaser images (will be unblocked))
cdn.podigee.com # (301 Moved Permanently - unimportant)

io is just a placeholder/redirect -> to *.com

**Comment by KodoPengin** [comment]
Well, i also have PI-Hole but it's inactive atm because it has no use for me. Will enable it in future for testing.

The problem with PI and other resolvers are that they can't display any stuff, Just hostnames.

To quote "Sure there is a bit of analytics and advertising involved but". Well, a bit, is a bit, and a bit multiplied by millions is a bit more. Be secure and keep privacy or keep your compfort and useless entries? It's never easy. 

But promised i will take a look in future again into PI. This also applies to other entries you posted. Unfortunately you (or others) have to wait till than. Will update the files further

**Comment by KodoPengin** [comment]
io.podigee.net will be unblocked next update

**Comment by KodoPengin** [comment]
Issue is fixed since the last update today
