### ISSUE TITLE
Don't break Video Conferences (stun.l.google.com)

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#14]
TURN and STUN Servers are vital in these days to use WebRTC based tools behind various forms of NAT and Firewalls
```stun.l.google.com``` shouldn't be on the lists therefore

**Comment by KodoPengin** [comment]
Hmm, difficult.

At least for games and software it's blocked because it's an unnecessary connection and not required to run a game/software.

Another reason is to grant more privacy (e.g. WebRTC leaks, device access), so it's blocked. There is no reason to allow the connections at this time.

Those have to be allowed manually.

Related entries can be found in
- Dying Light
- 20XX
