### ISSUE TITLE
No PTR Testing possible with test.actual.battle.net

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#15]
Removing ```test.actual.battle.net``` makes it possible again to log into wow test realms
i guess ```cn-test.actual.battle.net``` is the counter part for asia.
Otherwise you get a connection failed error when looking for realms.

**Comment by KodoPengin** [comment]
Since i have not accept the privacy agreement in January 2022, i actually can't test the Battle.net - Unfortunately, I don't know yet if and when I will do it again.

Since they have moved their headquarters from France to UK and are therefore outside the european data protection laws (i guess because of the Microsoft deal), this is a topic in itself.

Meanwhile, the entry must be removed manually.
