### ISSUE TITLE
remote-config.gog.com is allowed, its cname isn't

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#18]
Galaxy 2.0 has issues because ```remote-config.gog.com``` gets blocked via ```a1847.b.akamai.net```

**Comment by KodoPengin** [comment]
Will be fixed next update/s. 

Remote is a necessary connection if you want use GoG Services. In addition, the data for the Galaxy client will be renewed as soon as I find time. As i already have mentioned in the other posting. It's not forgotten.

Still have to sort the entries and bring them into shape. Currently i have tons of work with the whole project ;]

-

Beware also the following. As in the example, the addresses (users/remote) are not blocked, but the endpoints are, this does not interfere. At least, and this is important: the hosts entries themselves or normal use, because users can do what they do as usual.

But anything beyond? Like with DNS resolvers? That may be another story ^^
