### ISSUE TITLE
Firebase & Notifications

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#29]
An App that wants to subscribe to the FirebaseCloudMessaging system for push notifications needs ```firebaseinstallations.googleapis.com``` in all or at least multiple cases according to `https://www.kuketz-blog.de/google-firebase-zwingend-erforderlich-fuer-den-empfang-von-push-nachrichten/`
This in itself doesn't constitute tracking or advertising.
I think you should remove it

**Comment by yoshimo** [comment]
Infos about the domains and ports used:
`https://firebase.google.com/docs/cloud-messaging/concept-options#messaging-ports-and-your-firewall`

**Comment by KodoPengin** [comment]
Remains blocked, Tracker
{
	"name": "xxxx",
	"fid": "xxxxx",
	"refreshToken": "xxxxx",
	"authToken": {
		"token": xxxxx",
		"expiresIn": "604800s"
	}
}
{
	"projectId": "walkthrough-tool",
	"appId": "xxxxx",
	"databaseURL": "https://walkthrough-tool.firebaseio.com",
	"storageBucket": "walkthrough-tool.appspot.com",
	"locationId": "asia-northeast1",
	"authDomain": "walkthrough-tool.firebaseapp.com",
	"messagingSenderId": "xxxx",
	"measurementId": "G-9Q92J04VDB"
}

**Comment by KodoPengin** [comment]
https://www.bleepingcomputer.com/news/security/us-senator-govts-spy-on-apple-google-users-via-mobile-notifications/

**Comment by yoshimo** [comment]
Are a few apps that forgot to opt into encryption worth breaking the battery saving aspect for all other applications?

**Comment by KodoPengin** [comment]
Uhm sorry, currently I'm at a loss when it comes to the translation? What do you mean?

**Comment by yoshimo** [comment]
Die Push Nachrichten einiger Anwendungen nutzen keine Verschlüsselung und übertragen Klartext. Das is natürlich schlecht.
Andererseits frisst es deutlich an Strom wenn jede Anwendung regelmäßig Polling betreibt um über Nachrichten auf dem Laufenden zu bleiben. Hier würde Firebase Cloud Messaging deutlich den Energiebedarf reduzieren da es eine Komponente für alle Anwendungen übernimmt.
Hier zu argumentieren dass einige wenige Anwendungen nicht ordentlich arbeiten um den großen Rest als Kollateralschaden mitzunehmen finde ich jetzt nicht richtig.

**Comment by KodoPengin** [comment]
Danke ;]

Die Frage unabhängig dessen wäre generell eh, ob ein Mehrwert gegeben ist. Aus meiner Sicht nicht. Für Anwender schon gar nicht.

Ich habe da nicht gesagt, dass einige Applikationen nicht ordentlich arbeiten.

Sie sind generell unnötig, geben einem Konzern mehr Daten als diesem zusteht (vor allem ohne Zustimmung), jede Applikation mit Firebase kontaktiert zu Start erstmal Google) und oftmals auch während der gesamten Laufzeit, die Dienste tragen zur Gängelung (Push-Nachrichten) mit bei und eben damit auch zum erhöhten Stromverbrauch (sofern dieser überhaupt gegeben ist), werden mitunter als Tracker und Werbemittel ausgeliefert und zuguter Letzt für staatliche Überwachung abgefischt. Nicht zu vergessen, Abhängigkeit vom Gerät selbst.

Leider kommt seit den Snowden-Leaks nur noch wenig ans Tageslicht, sodass die genannte News eher die Ausnahme ist. Wer wie hier z.b. auf Firebasedienste angewiesen ist, muss manuell freischalten.

Alles in Allem, ist manchmal weniger mehr.

--

Thank you ;]

The question, regardless of that, would generally be whether there is any added value. In my opinion, there isn't. Especially not for users.

I didn't say that some applications don't work properly.

They are generally unnecessary, providing a corporation with more data than it deserves (especially without user-consent). Every application using Firebase contacts Google first at the start and often also during the entire runtime. These services contribute to coercion (push notifications) and, therefore, increased power consumption (if this is given at all). They are sometimes delivered as trackers and advertising tools and, last but not least, they are misused for state surveillance. Not to forget, dependence on the device itself.

Unfortunately, since the Snowden leaks only little comes to light, so that the mentioned news is rather the exception. Anyone who is dependent on Firebase services, for example, must unlock manually.

All in all, sometimes less is more.
