### ISSUE TITLE
cdn.delight-vr.com false positive

### ISSUE THREAD

**Issue by RichardBeisser** [KodoPengin/GameIndustry-hosts-Template#32]
Hello,

I think cdn.delight-vr.com is a false positive.
It is used to host and serve video-content

example:
https://efahrer.chip.de/news/autohaus-verrottet-seit-jahrzehnten-trotzdem-stehen-dort-noch-neuwagen_1015873

**Comment by KodoPengin** [comment]
Hey there,

You may have right, but it's no false positive. Mentioned adress contains beside of serving videos - Event, Click and UTM tracking. 2 Scripts are there:

https://cdn.delight-vr.com/latest-bf/dl8enabler.js
https://cdn.delight-vr.com/latest-bf/dl8-2a95c197d48298ac0cab8b68f7f89601a9f14059.js

**Comment by RichardBeisser** [comment]
> Unfortunately, this is a case of: Either security and privacy protection against tracking or you allow everything and have comfort functions for it
> 
> However, I can attach a note behind the corresponding address in the next update (will be made over the upcoming holidays)

Hi,
Thanks for explanation. I agree with you, in this case, it is correct when there are tracking-scripts. So it should remain in list.

**Comment by KodoPengin** [comment]
Unfortunately, such a decision is always difficult what is blocked or not and all the more difficult when tracking, analytics and advertising are tied with content. Whether it's websites or software (programs and games).

All links in the filter files are manually checked and entered in the list. Nothing is hastily blocked and, in case of doubt, checked several times and I try to make it as easy as possible for users just by sorting through categories or comments.

On the other hand, it shows how broken the Internet is these days.

An update has just been released. There will be another one shortly, in which the last checked programs will be added to the filter list.

Anyways, thanks for the feedback, because the up-to-date entries could therefore be verified again

With this in mind, a few nice holidays, or merry Christmas ;]
