### ISSUE TITLE
Dubious and misleading consentmanager (Title edited by Pengin)

### ISSUE THREAD

**Issue by RichardBeisser** [KodoPengin/GameIndustry-hosts-Template#33]
Hello,

at the moment, the list blocks
part-0017.t-0009.t-msedge.net
I suppose this is a false positive.
F. ex. this blocks login at https://www.lichtblick.de/konto/

**Comment by KodoPengin** [comment]
I suspect that the cookie consent does not work properly because Usercentrics is blocked in the lists. The following are called on the page (without consent and visible nag screen):

www.lichtblick.de
fast.fonts.net # CSS, Cookies
www.datadoghq-browser-agent.com # Logging
app.usercentrics.eu # Tracking pixel, bundle.js
api.aklamio.com # Tracker
analytics.aklamio.com # Tracker
api.usercentrics.eu # Cookie Nagscreen Translation / Übersetzung
aggregator.service.usercentrics.eu # Tracker list / Auflistung
www.googletagmanager.com # 2 Trackers (GTM-WMPC837, GTM-PH88SK)
consent-api.service.consent.usercentrics.eu # Consent / Zustimmung
uct.service.usercentrics.eu # Tracking pixel
graph.lichtblick.de # Login
mein.lichtblick.de # Real login / Anmeldung, Kontologin, fonts, jpg
graphql.usercentrics.eu # Logger / Targets

Since I don't have an account there, feel free to test it out and provide feedback so that I can adjust the files.

**Comment by RichardBeisser** [comment]
just noticed, Stiftung Warentest use it as well:
https://www.test.de/CO2-Steuer-einfach-erklaert-5915840-0/
https://www.test.de/E-Rezept-Wann-geht-es-endlich-los-5862837-0/

**Comment by KodoPengin** [comment]
The fundamental problem with these "consents" is that trackers and services are contacted, tracking pixels and other mechanisms are activated before users can give their consent.

Users are often lied to and misled about purposeful and real data collection. And in the case of someone wanting their data deleted, on websites with up to 100+ services, who is going to chase after and contact each individual company for data requests and deletion? I know none.

Responsible on Test:
https://a.delivery.consentmanager.net
https://cdn.consentmanager.net

https://www.test.de/cookie-richtlinie/

Consent is blocked? Why? Because cookie banners are simply a farce, and trackers and analytics are still active. 

Specifically, in the case of test.de, the following things are active directly upon page load WITHOUT consent:

Piano Analytics + Activation
https://experience-eu.piano.io
https://cdn-eu.piano.io
https://c2-eu.piano.io
https://cdn.cxense.com

Piano DMP
https://comcluster.cxense.com

These services are also blocked. In a sense, the list does exactly what it is supposed to do.

The fact that a necessary page function may no longer function is, of course, a separate issue.

And as mentioned here, the service from Piano is definitely not among "technically necessary cookies or services" that are required for a login. It would be advisable to write to the site operators regarding this matter.

Log talk, short sense, a final update for this year will be provided later in the day. I will assess it once again. Either it will be activated, or a note will be made.

**Comment by KodoPengin** [comment]
Title edited and closed

**Comment by RichardBeisser** [comment]
Hallo,

erst einmal ein Gutes Neues Jahr.

Vielen Dank für die Erläuterungen.

Zum Thema Cookie.
Ich verwende im Heimnetz ein PiHole, in den Browsern U-block, I don't care about cookies und den CanvasBlocker.
Als Anwender habe ich schnell nach der Einführung der Cookie-Banner festgestellt dass man den Cookie-Bannern nicht mit der Blokade von Domänen begegnen darf (also mit dem PiHole) weil dann viele Seiten nicht mehr funktionieren. Vielmehr braucht man Werkzeuge die den Seitencode untersuchen und darauf reagieren - deshalb u-block und das Addon von Daniel Kladnik.


Die Domain part-0017.t-0009.t-msedge.net scheint der zentrale Anlaufpunkt auf vielen Webseiten zu sein. Wenn man den Dienst eines Anbieters (usercentrics ???) nutzen möchte, dann muss man wohl eine eigene Subdomain zur Verfügung stellen die als Cname auf die besagte Domain zeigt - zumindest wenn ich mir das im PiHole anschaue.
Im Fall von lichtblick.de ist das "anmelden.lichtblick.de", bei der Stiftung Warentest "cdn.test.de"
Kennst du da die Hintergründe?

Du hast viel zu Piano Analytics + Activation.
Wie du gesagt hast, deren Domänen stehen auch in der Blocklist und werden nach wie vor blockiert. Auf die Funktion der Webseiten hat dies keine Auswirkung.

t-msedge.net sagt mir dass die Dienste in der Cloud von Microsoft laufen.
Mein Gedanke war zum einen wer und zum anderen was hinter der Domain part-0017.t-0009.t-msedge.net steckt, und ob da wirklich Analytics und Trackings drüber laufen, oder ob das nur harmlose Dinge sind wie DDOS-Protection.
