### ISSUE TITLE
Invalid entries in Lists

### ISSUE THREAD

**Issue by RichardBeisser** [KodoPengin/GameIndustry-hosts-Template#39]
Hello,

some of your lists contains invalid entries.

Examples:
  [i] Target: https://github.com/KodoPengin/GameIndustry-hosts-Template/blob/master/Main-Template/hosts?raw=true
  [i] Target: https://raw.githubusercontent.com/KodoPengin/GameIndustry-hosts-Template/master/Gaming-Full-Template/hosts
      Sample of non-domain entries:
        - "﻿"
        - "unity-ams1-ip-holder"

  [i] Target: https://hosts.gameindustry.eu/abusive-adblocking/dl/
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 97 non-domain entries)

  [i] Target: https://hosts.gameindustry.eu/adobe-inc/dl/
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 9 non-domain entries)
      Sample of non-domain entries:
        - "�9�a^���"
        - "�\d�  

  [i] Target: https://hosts.gameindustry.eu/amazon-com-inc/dl/
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 12 non-domain entries)
      Sample of non-domain entries:
        - "7z��'"
        - "@a�<�"
        - "mj�Ϲ)k��y��hm�wۦ��zz�i�;��8�"
        - "�]dy��t�n�6w�>7��k囂��jԸ����v��0"
        - "���x%���*mdd"

  [i] Target: https://hosts.gameindustry.eu/ministerien-und-behoerden/dl/
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 12 non-domain entries)
      Sample of non-domain entries:
        - "�9�a^���"
        - "��҃(��t�ݑxcr�*��1+���ab_万l���6����k���_�y�q���/��>)�)�=�8��"
        - "�j�mn~x��n�$����s��)�`�hԜ�����zy?i�j�ix�9jw��o"
        - "��m�w����"
        - "]�"

  [i] Target: https://hosts.gameindustry.eu/pc-full-template/dl/
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 455 non-domain entries)
      Sample of non-domain entries:
        - "�9�a^���"
        - ">�"
        - "@�}��m��"
        - "�8�"
        - "���k:4"

  [i] Target: https://hosts.gameindustry.eu/schutz-gegen-serverangriffe/dl/
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 53 non-domain entries)
      Sample of non-domain entries:
        - "y��8i�"
        - "j�3f��м�l��7d�"
        - "�˂3��eo�k�z"
        - "�n"
        - "�t>�"

  [i] Target: https://hosts.gameindustry.eu/staedte-und-gemeinden/dl/
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 25 non-domain entries)
      Sample of non-domain entries:
        - "�9�a^���"
        - "u�涬�y����z��g�s;x"
        - "l�eu�"
        - "n��vp"
        - "+f�ؖ�}�"

**Comment by KodoPengin** [comment]
Hello Richard.

unity-ams1-ip-holder is addressed and contacted directly from the game in the same way. even if it may be invalid. Tracing also gave the same result.

--

Regarding the other messages, this is because you are trying to read/import packed files.

Since my system was spammed from automatic queries and bots, the download mechanics were replaced some time ago.

**Comment by RichardBeisser** [comment]
> Regarding the other messages, this is because you are trying to read/import packed files.

Hello,
thanks for fast reply.

You are right. I am using PiHole and I thought pihole's developer have implented support for packed files, but this is not the case. Do you have any idea how I can use your lists in Pihole?

**Comment by KodoPengin** [comment]
I'll have another look with PI-Hole in the next few days, but I can't promise anything. Will report back here again.

**Comment by KodoPengin** [comment]
As for the 'unity-ams1-ip-holder', it will be deleted with the next update. Since Path of Exile has started a new season, some entries have changed since the last test, including the mentioned entry. While searching for the current endpoints, a similar entry was found again. However, this will no longer be listed. Older entries for the game, such as for the Chinese version, will also be deleted as I no longer use the Chinese platform and therefore cannot test it.

As for some of the other templates, the current download-system will be kept. However, there is currently a consideration to merge some of the files into the main one. This would accordingly also benefit the GitHub downloaders.

Others need to be updated to the latest version, which is currently not (or only partially) possible for me. Device-related and time-related.
