### ISSUE TITLE
Gaming-Mini-Template  linking epic to the Rockstar launcher block 

### ISSUE THREAD

**Issue by trenton4k** [KodoPengin/GameIndustry-hosts-Template#5]
Gaming-Mini-Template 
linking epic accounts to the Rockstar launcher block (Red Dead Redemption 2) 
api.epicgames.dev

**Comment by KodoPengin** [comment]
Well it was not really an mistake, because Epic's behaviour with **** consumers with forced (always) online mode and (datarouter)telemetry linked together. Well, nothing new that many games these days won't work with blocked spyware from that company. 

I have adapted the block now as it can be found in the main template, only slightly shortened. Should be enough ;]

Use of Epic Games, Inc. products or Unreal Engine titles at your own risk. Same counts for related entries in my lists. Handling according to own needs.

For those who want to preserve own privacy, have to be aware that many products only work half the time or not at all anymore with a blocked api.
