### ISSUE TITLE
Suggestion possible source

### ISSUE THREAD

**Issue by gallegonovato** [KodoPengin/GameIndustry-hosts-Template#9]
Good afternoon:

First of all thank you very much for all your work and effort.

If I may, I would like to make a suggestion. From a source I found that could help you in your hosts.

This font is:

https://github.com/ookangzheng/blahdns ( https://blahdns.com/ )

I do not know if some entries that they have in blocked and in their white list, could help you?

Best regards

**Comment by KodoPengin** [comment]
Good afternoon back, gallegonovato ;]

Actually my list is handmade. Apart from one exception (certain entries on online-metrix which are also marked) everything has been compiled and checked by myself during the years without using other lists.

That's where I would like to remain independent and is one aspect which makes my list unqiue from others

Entries are added as soon as I encounter them by myself or are sent to me for review. Even if that means that I have less to offer... but more specialized.

If BlahDNS wants to use my lists for their project, they can do it as long as long as they follow the rules - CC BC-NC-SA

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for your time and response.

I am sorry if I did something wrong. I just wanted to try to help you in your work. And the fact that you make your lists DESERVES ALL MY ADMIRATION AND TO TAKE YOUR HATS OFF TO YOU.

By the way I wanted to tell you about some connections I detected.

For example Adaway app.adaway.org call home to find out if there are updates or not. Even unchecking automatic updates.

From Sd Maid piwik.darken.eu 

From whatsapp privatestats.whatsapp.net

Google: g.co , chromeenterprise.google , googleapis.co , googlecdn.org , 
googlecloudpresscorner.com , research.google ,tv.google , stories.google , sre.google

I don't know if they can help you.

Thank you very much for all your hard work and effort.

**Comment by KodoPengin** [comment]
No worry. Everything is fine ;]

It's only hard to understand you sometimes....

Normally those programs shouldn't phone anywhere... except update routines and than it's depending where the lists are and how often.

Well since Ghostery and Adblock+? sold userdata, that was one reason why i started this project. Because you can only trust in things you made by yourself...

Unfortunately i can not test Adaway because my device is incompatible >.<

Piwik is Matomo... should be blocked by default.... i can add this entry for the next update.... The Google domains, well. would be interesting what you use. Here or per E-Mail. What you prefer.

From what i see here it's no harmfull stuff... but i bet unnecessary for actual program operation ;]

**Comment by gallegonovato** [comment]
Good afternoon @KodoPengin

I upload some screenshots of connections I found.

They would be:

https://ibb.co/hYnsRyk
https://ibb.co/LdRmDLQ
https://ibb.co/6DbJqn8
https://ibb.co/bHP4Bp3
https://ibb.co/2SFHzW4
https://ibb.co/mBXYWN7
https://ibb.co/GpYryG4
https://ibb.co/8sWM49j
https://ibb.co/xFFdFLd
https://ibb.co/ZJBGHcn
https://ibb.co/R0nyftG
https://ibb.co/gtd82WR
https://ibb.co/Cndh5XY
https://ibb.co/mXndC4x
https://ibb.co/rGJtVph
https://ibb.co/Lr2TTyH
https://ibb.co/gSXFpxH
https://ibb.co/WDjRwKc
https://ibb.co/8YPj1j1
https://ibb.co/KscDhBL
https://ibb.co/k32BSgK
https://ibb.co/YphHb8R
https://ibb.co/HgRbkJ9
https://ibb.co/sKr2BtB
https://ibb.co/cTf251c
https://ibb.co/dLH6pcv
https://ibb.co/GJSLHS4
https://ibb.co/v33nG6C
https://ibb.co/vDdmfsk
https://ibb.co/PhmfqpD
https://ibb.co/PthssBR
https://ibb.co/VTnbm0Y
https://ibb.co/0tpMnnx
https://ibb.co/W65QY2F
https://ibb.co/VpXpkGr
https://ibb.co/gtd82WR
https://ibb.co/Cndh5XY
https://ibb.co/mXndC4x
https://ibb.co/rGJtVph
https://ibb.co/Lr2TTyH
https://ibb.co/gSXFpxH
https://ibb.co/WDjRwKc
https://ibb.co/8YPj1j1
https://ibb.co/KscDhBL
https://ibb.co/k32BSgK
https://ibb.co/YphHb8R
https://ibb.co/HgRbkJ9
https://ibb.co/sKr2BtB
https://ibb.co/cTf251c
https://ibb.co/dLH6pcv
https://ibb.co/GJSLHS4
https://ibb.co/v33nG6C
https://ibb.co/vDdmfsk
https://ibb.co/PhmfqpD
https://ibb.co/PthssBR
https://ibb.co/VTnbm0Y
https://ibb.co/0tpMnnx
https://ibb.co/W65QY2F
https://ibb.co/VpXpkGr
https://ibb.co/RYmdpZ5

A hug

**Comment by gallegonovato** [comment]
Good afternoon @KodoPengin 

I would like to take this opportunity to comment on possible new connections:

s-beta.amazon-adsystem.com
300zlf-dnsotls-ds.metric.gstatic.com
cdn.fastclick.net
e.crashlytics
gstaticadssl.l.google.com
KQu0cL-dnsotls-ds.metric.gstatic.com
media.fastclick.net
optimizationguide-pa.googleapis.com
passwordsleakcheck-pa.googleapis.com
peoplestackwebexperiments-pa.clients6.google.com
pf-in-f188.1e100.net
sa-in-f188.1e100.net
tg-in-f188.1e100.net
wa-in-f188.1e100.net
wl-in-f188.1e100.net
wq-in-f188.1e100.net
www-google-analytics.l.google.com
alt5-mtalk.google.com.access.network
r2---sn-4g5edn6k.googlevideo.com.access.network
r5---sn-25ge7nsl.googlevideo.com.access.network
r5---sn-25glen7y.googlevideo.com.access.network
inapps.appsflyer-cn.com
sf3-fe-tos.pglstatp-toutiao.com
skadsdk.appsflyer-cn.com
firebase-settings.crashlytics.com
tpstelemetry.tencent.com
access.toggle.qq.com
event.toggle.qq.com
log.tbs.qq.com
ws.tapjoyads.com
configv2.unityads.unity3d.com
init.supersonicads.com
teleport.soom.la
networksdk.ssacdn.com
api.vungle.com
int.akisinn.site
connect.tapjoy.com
pm-gateway.supersonicads.com
publisher-config.unityads.unity3d.com
events.mz.unity3d.com
auction-load.unityads.unity3d.com
nginx-auction7-prd.unityads.unity3d.com
auiopt.unityads.unity3d.com
cdn2.inner-active.mobi
cdn-creatives-akamaistls-prd.acquire.unity3dusercontent.com
www.antutu.com.bsgslb.cn 
zcmglobal.v.bsgslb.cn
www.98w.com
98w.com
www.pcwatch.com
unityads.unity3d.com
unityads.unitychina.cn
uniqodo.com
unknownads.com
urbanairship.com
urgent-test-kit.com # Covid phishing
us-east-tlx.3lift.com
us-west-tlx.3lift.com
usanaly.accio.ai


A hug

**Comment by KodoPengin** [comment]
Hello gallegonovato :]

thank you very much for the new stuff.

Well, some of your entries are already in the filter lists, I will have a look at others next time. I have just released a new update a few minutes ago for Main & gaming template and some stuff can be found already in the android files.

Actually i have no chance to check Androidconnections. New phone and not yet set up as a test environment.

The general problem is only (same counts for the pull requests), since I do not know where the entries come from I will not be able to trace and that in turn can theoretically bring difficulties for me as publisher. Especially when it comes to stuff like Google Endpoints "1e100.net" as example.

**Comment by gallegonovato** [comment]
Good afternoon @KodoPengin

First of all thank you very much for your time and work.

Regarding the connections, they are getting better and better in all aspects. Mozilla, Google, Meta, etc... Making it almost impossible to see a page and not get a connection to Google and youtube, even if there are no videos on that site. Not to mention applications that should not call anywhere and so they do.

I am currently using your hosts https://raw.githubusercontent.com/KodoPengin/GameIndustry-hosts-Template/master/Android-Full-Template/hosts , do you advise me to increase by putting https://raw.githubusercontent.com/KodoPengin/GameIndustry-hosts-Template/master/Main-Template/hosts ?

Also in the future, as long as my Nexus 6p will last with lineageos and no gaps. I would consider changing my phone but for a second hand one so I can put lineageos without anything from Google and using all open source. But I do not know which one to choose because the prices here are very very high even second hand. And new would be a hassle, since you have to endure the duration of the warranty and others without making many changes. And in the meantime there is no privacy.

Best regards

**Comment by KodoPengin** [comment]
You can merge the lists for yourself, especially since several services come from the same publishers. On my old phone i used the main template and both for Android. Worked fine together and shouldn't be a problem :]

In relation to Android i have to update them in future as well, but it well take time because there is a lot other stuff with much more priority.

Regards and take care
